accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signin/kakao/', views.Kakao_login, name = "kakao_signin"),
    path('signin/kakao/callback', views.Kakao_login_callback, name="kakao_signin_callback"),
    path('signout/', auth_views.LogoutView.as_view(), name='signout'),
    path('user_info/', views.user_info, name = "user_info"),    
    path('edit_info/<str:method>', views.edit_info, name = "edit_info"),    
]

shops/urls.py
from django.urls import path, re_path
from . import views
app_name = 'shops'

urlpatterns = [
    path('register/', views.shop_register, name = "register"),
    path('<int:shop_id>/',views.shop_admin_view,name="admin"),
    path('<int:shop_id>/settings/',views.shop_settings,name="settings"),
    path('<int:shop_id>/status/',views.set_shop_status,name="status"),
    
    
    path('<int:shop_id>/settings/location',views.shop_settings_location,name="location"),
    
    path('<int:shop_id>/remove/',views.shop_remove,name="shop_remove"),    
    path('render_list/',views.get_waiting_list,name='get_waiting_list'),
    path('remove',views.remove_waiting,name='remove'),
    path('call',views.call_waiting,name='call'),
    path('enter',views.enter_waiting,name='enter'),
    path('get_shops/',views.get_shops,name='get_shops'),
    path('get_address/',views.get_address,name='get_address'),
    path('get_biznum/',views.get_biznum,name='get_biznum'),
    path('filtered_shop',views.filter_shop,name='filter'),
    
    
    path('test',views.test,name='test'),
]

waitinghow/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from shops import views as shop_views
from clients import views as clients_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shops/', include('shops.urls')),
    path('waitings/', include('waitings.urls')),
    path('clients/', include('clients.urls')),
    path('infocards/', include('infocards.urls')),
    path('',clients_views.search_shops,name='search_main'),
    path('user_info',clients_views.search_shops,name='user_info'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waitings/urls.py
from django.urls import path, re_path
from . import views

app_name = 'waitings'
#
urlpatterns = [
    path('<int:shop_id>/views', views.customer_views, name = "views"),
    path('<int:shop_id>/add/waiting', views.add_waiting, name = "add_waiting"),
    path('<int:shop_id>/add/people', views.add_people, name = "add_people"),
    path('showteams/',views.show_teams,name="show_teams"),
    path('<int:shop_id>/add/remote',views.customer_views,name="remote")
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import authenticate, login
from django.db import models
from django.db.models import QuerySet
from django.http import HttpRequest
from datetime import datetime as dt
# Create your models here.#
class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = "M", "남성"
        FEMALE = "F", "여성"
    class ProviderTypeCodeChoices(models.TextChoices):
        LOCAL = "local", "로컬"
        KAKAO = "kakao", "카카오"

    gender = models.CharField('성별', max_length=1, blank=True, choices=GenderChoices.choices)
    avatar = models.ImageField('아바타', blank=True, upload_to="accounts/avatar/%Y/%m/%d", help_text="100px * 100px 크기의 gif/png/jpg 이미지를 업로드해주세요.")
    provider_type_code = models.CharField('프로바이더 타입코드', max_length=20, choices=ProviderTypeCodeChoices.choices,default=ProviderTypeCodeChoices.LOCAL)
    provider_accounts_id = models.PositiveIntegerField('프로바이더 회원번호', default=0)
    #has_shop은 추후삭제예정.
    @staticmethod
    def login_with_kakao(request: HttpRequest, provider_accounts_id):
        provider_type_code = User.ProviderTypeCodeChoices.KAKAO
        qs: QuerySet = User.objects.filter(provider_type_code=provider_type_code,
                                           provider_accounts_id=provider_accounts_id)

        if not qs.exists():
            username = provider_type_code + "__" + str(provider_accounts_id)
            name = provider_type_code + "__" + str(provider_accounts_id)
            email = ""
            password = ""
            user: User = User.objects.create_user(username=username, email=email, password=password,
                                                  first_name=name,
                                                  provider_type_code=provider_type_code,
                                                  provider_accounts_id=provider_accounts_id)
        else:
            user: User = qs.first()

        login(request, user)
    def have_shop(self):
        if len(self.shop_set.all()) >= 1:
            return True
        else:
            return False
    def checker(self):
        return self.is_authenticated
    def where_waiting(self):
        """
        test
        """
        waitings = dir(User.objects.select_related())
        return waitings

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from accounts.models import User


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'first_name', 'last_name','shop_name']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email

class IdfinderForm(forms.ModelForm):
    class Meta:
        model = User  # 사용할 모델
        fields = ['email']

accounts/views.py
from django.shortcuts import render,redirect, resolve_url
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.http import HttpRequest
from django.contrib import messages
from accounts.models import *
from shops.models import Shop
from waitings.models import Waiting
from .models import *
import requests,os

# Create your views here.
def user_info(request):
    user = request.user
    context={}
    if user.is_authenticated:
        ##유저가 가지고있는 waitings의 id값을 가져옴.
        ## waitings가 가지고 있는 shop의 waitings에서 id값보다 낮은 객체들 필터
        waitings = request.user.waitings_set.filter(is_disposed=False)
        #waiting = waitings.first()
        #shop_waiting = waiting.shop_name.waiting_set.filter(id__lt = waiting.id,is_disposed=False).count()
        context.update({'waitings':waitings})
        if user.have_shop:
            shops_list = Shop.objects.filter(master=user)
            context.update({'shops_list': shops_list})
            return render(request,'accounts/user_info.html',context)
        return render(request,'accounts/user_info.html',context)
    else:
        messages.success(request,"로그인실패")
        return render(request,'accounts/user_main.html')
    
def Kakao_login(request : HttpRequest):
    REST_API_KEY = os.environ.get("WAITING_HOW__REST_API_KEY")
    REDIRECT_URI = os.environ.get("WAITING_HOW__LOGIN_REDIRECT_URI")
    next_url = request.GET.get('next')
    kakao_auth_api = "https://kauth.kakao.com/oauth/authorize?"
    return redirect(
        f"{kakao_auth_api}client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code&state={next_url}"
    )
def Kakao_login_callback(request):
    code = request.GET.get("code")
    REST_API_KEY = os.environ.get("WAITING_HOW__REST_API_KEY")
    REDIRECT_URI = os.environ.get("WAITING_HOW__LOGIN_REDIRECT_URI")
    token_request = requests.get(
        f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&code={code}"
    )

    token_json = token_request.json()

    error = token_json.get("error", None)
    if error is not None:
        raise Exception('카카오 로그인 에러')

    access_token = token_json.get("access_token")

    profile_request = requests.get(
        "https://kapi.kakao.com/v2/user/me",
        headers={"Authorization": f"Bearer {access_token}"},
    )
    profile_json = profile_request.json()

    id = profile_json.get("id")

    User.login_with_kakao(request, id)
    user = User.objects.get(provider_accounts_id=id)
    messages.success(request, f"{user.username}님 카카오톡 계정으로 로그인되었습니다")
    next_url = request.GET.get('state')
    if next_url.lower() != "none":
        return redirect(next_url)
    return redirect("accounts:user_info")

def edit_info(request,method):
    if method == "POST":
        pass
    elif method == "GET":
        return render(request,'accounts/edit_info.html')

templates/accounts/edit_info.html
{% extends 'accounts/layout.html' %}
{% block content%}
<div class="flex flex-jc-c">
    <div>
        <a class="register-shop gotgam" href="{% url 'shops:register' %}"><i class="fas fa-home"></i>매장등록</a>
    </div>
    <div>
        <a class="delete-shop gotgam" href="{% url 'shops:shop_remove' 0 %}"><i class="fas fa-times"></i>매장삭제</a>
    </div>
</div>

{% endblock %}

templates/accounts/layout.html
{% extends 'layout.html' %}
{% load static %}
{% block head_scripts %}
{% block scripts %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}
{% endblock %}
{% block head_styles %}
{% block styles %}
{% endblock %}
{% endblock %}
{% block app %}
{% block content %}
{% endblock %}
{% endblock %}
{% block foot_scripts %}
{% block _scripts %}
{% endblock  %}
{% endblock %}

templates/accounts/user_info.html
{% extends 'accounts/layout.html' %}
{% block app %}
{% load accounts_filter %}
<div>
    <ul>
        <li>
            {% if waitings %}
            <div>{{request.user}}님의 예약현황</div>
            {% for waiting in waitings %}
            <div>매장 : {{waiting.shop_name}}</div>
            <div>남은 대기열 : {{waiting|get_count}}</div>
            {% endfor %}
            {% endif %}
        </li>
        <li class="flex flex-jc-c">
            <a class="searchButton w-500" href="{% url 'accounts:edit_info' 'GET' %}">
                <i class="fas fa-edit gotgam">매장등록</i>
            </a>
        </li>
        <li class="flex flex-jc-c">
            {% if request.user.have_shop %}
            <div class="card-con mx-w">
                {% for shop in shops_list %}
                <div class="shop-card">
                    <span  class ="title gotgam spaces">{{shop.name}}</span>
                    <a class="elements spaces" href="{% url 'waitings:views' shop.id  %}">대기열 받기</a>
                    <a class="elements spaces" href="{% url 'shops:admin' shop.id  %}">대기열 관리</a>
                    <a class="elements spaces" href="{% url 'shops:settings' shop.id  %}">수정</a>
                    {% if shop.is_active %}
                    <a class="elements spaces safe" href="{% url 'shops:status' shop.id %}">영업중</a>
                    {% else %}
                    <a class="elements spaces warn" href="{% url 'shops:status' shop.id %}">영업종료</a>
                    {% endif %}
                </div>    
                {% endfor %}
            </div>
            {% else %}
            {% endif %}
        </li>
    </ul>
</div>
{% endblock %}

templates/accounts/user_main.html
{% extends 'layout.html' %}
{% block app %}

<div id="login-box">
    <h2 class="tit gotgam">LOGIN</h2>
    <div class="kakao-login-btn flex">
        <a class="flex flex-jc-c flex-ai-c" type='submit' href = "{% url 'accounts:kakao_signin' %}"><i class="fas fa-comment"></i>카카오로그인</a>
    </div>
</div>
{% endblock %}