infocards/urls.py
from django.urls import path, re_path
from . import views
from . import models
app_name = 'infocards'

urlpatterns = [
    path('<int:shop_id>/settings/infocards',views.infocard,name="infocard"),
    path('<int:shop_id>/settings/menu/remove',views.menu_remove,name="menu_remove"),
    path('<int:shop_id>/settings/info',views.info,name="info"),    
    path('<int:shop_id>/settings/info_edit/<int:info_id>',views.info_edit,name="info_edit"),
    path('<int:shop_id>/settings/info_remove/<int:info_id>',views.info_remove,name="info_remove"),
]

shops/urls.py
from django.urls import path, re_path
from . import views
app_name = 'shops'

urlpatterns = [
    path('register/', views.shop_register, name = "register"),
    path('<int:shop_id>/',views.shop_admin_view,name="admin"),
    path('<int:shop_id>/settings/',views.shop_settings,name="settings"),
    path('<int:shop_id>/status/',views.set_shop_status,name="status"),
    
    
    path('<int:shop_id>/settings/location',views.shop_settings_location,name="location"),
    
    path('<int:shop_id>/remove/',views.shop_remove,name="shop_remove"),    
    path('render_list/',views.get_waiting_list,name='get_waiting_list'),
    path('remove',views.remove_waiting,name='remove'),
    path('call',views.call_waiting,name='call'),
    path('enter',views.enter_waiting,name='enter'),
    path('get_shops/',views.get_shops,name='get_shops'),
    path('get_address/',views.get_address,name='get_address'),
    path('get_biznum/',views.get_biznum,name='get_biznum'),
    path('filtered_shop',views.filter_shop,name='filter'),
    
    
    path('test',views.test,name='test'),
]

waitinghow/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from shops import views as shop_views
from clients import views as clients_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shops/', include('shops.urls')),
    path('waitings/', include('waitings.urls')),
    path('clients/', include('clients.urls')),
    path('infocards/', include('infocards.urls')),
    path('',clients_views.search_shops,name='search_main'),
    path('user_info',clients_views.search_shops,name='user_info'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infocards/models.py
from django.db import models
from shops.models import Shop
# Create your models here.
class Info(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    image = models.ImageField('소개사진',upload_to="infos/info/%Y/%m/%d",blank=True,null=True)
    content = models.TextField('소개글')
    
class Category(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField('매장이름',max_length=100)
    @classmethod  
    def is_name(cls,cat_name):
        try:
            Category.objects.get(name=cat_name)
            return False
        except:
            return True
    
    def __str__(self):
        return f"{self.name}"
    
class Menu(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField('메뉴사진',upload_to="infos/menu/%Y/%m/%d",blank=True,null=True)
    name = models.CharField('메뉴이름',max_length=100)
    content = models.CharField('메뉴설명',max_length=100,blank=True,null=True)
    price = models.PositiveIntegerField('메뉴가격')
    @classmethod  
    def is_name(cls,men_name):
        try:
            Menu.objects.get(name=men_name)
            return False
        except:
            return True
    def __str__(self):
        return f"{self.name}"

infocards/forms.py
from django import forms
from .models import *
class CategoryRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = True

    class Meta:
        model = Category
        fields = ['name']
        
class MenuRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = True

    class Meta:
        model = Menu
        fields = ['name']
        
class InfoRegisterForm(forms.ModelForm):
    
    class Meta:
        model = Info
        fields = ['image','content']

infocards/views.py
from multiprocessing import context
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib import messages
from shops.functions import *
from .forms import *
from .models import *
from shops.models import *
# Create your views here.

def infocard(request,shop_id):
    shop=get_shop(request,shop_id)
    infos = shop.category_set.all()
    if  request.POST.get("type") == "category" and request.method == 'POST':
        cat_form = CategoryRegisterForm(request.POST)
        cat_name = request.POST.get('name')
        if not Category.is_name(cat_name):
            messages.warning(request,f"{cat_name} 카테고리가 존재합니다.")
            return redirect('infocards:infocard',shop_id)
        if cat_form.is_valid():
            category = cat_form.save(commit=False)
            category.shop = shop
            category.save()     
            return redirect('infocards:infocard',shop_id)   
    else:
        cat_form = CategoryRegisterForm()
        
    if request.POST.get("type") == "menu" and request.method == 'POST':
        men_form = MenuRegisterForm(request.POST)
        men_name = request.POST.get('name')
        if not Menu.is_name(men_name):
            messages.warning(request,f"{men_name} 메뉴가 존재합니다.")
            return redirect('infocards:infocard',shop_id)
        if men_form.is_valid():
            menu = men_form.save(commit=False)
            menu.category = get_object_or_404(Category,id=request.POST.get('cat_id'))
            menu.content = request.POST.get('content')
            menu.price = request.POST.get('price')
            menu.save()
            return redirect('infocards:infocard',shop_id)
    else:
        men_form = MenuRegisterForm()
    context={'shop':shop,'men_form':men_form,'cat_form':cat_form,'infos':infos}
    return render(request,'infocards/infocards.html',context)


def menu_remove(request,shop_id):
    shop=get_shop(request,shop_id)
    if request.method == "POST":
        if request.POST.get('type')=='menu':
            menu = get_object_or_404(Menu,id=request.POST.get('men_id'))
            menu.delete()
            
        if request.POST.get('type')=='category':
            cat = get_object_or_404(Category,id=request.POST.get('cat_id'))
            cat.delete()
    context = {'shop':shop}
    return redirect('infocards:infocard',shop_id=shop_id)
    
@owner_required
def info(request,shop_id):
    shop = get_shop(request,shop_id)
    if request.method == "POST":
        info_form = InfoRegisterForm(request.POST,request.FILES)
        if info_form.is_valid():
            form = info_form.save(commit=False)
            form.shop = shop
            form.save()
            messages.success(request,"저장되었습니다.")
            return redirect('infocards:info',shop_id)
    else:
        info_form = InfoRegisterForm()
    context={'shop':shop,'form':info_form}
    return render(request,'infocards/setinfo.html',context)

@owner_required
def info_edit(request,shop_id,info_id):
    shop = get_shop(request,shop_id)
    info = get_object_or_404(Info,shop=shop,id=info_id)
    if request.method == "POST":
        info_form = InfoRegisterForm(request.POST,request.FILES,instance=info)
        if info_form.is_valid():
            form = info_form.save(commit=False)
            form.save()
            messages.success(request,"저장되었습니다.")
            return redirect('infocards:info',shop_id)
    else:
        info_form = InfoRegisterForm(instance=info)
    context={'shop':shop,'form':info_form}
    return render(request,'infocards/setinfo.html',context)
    
@owner_required
def info_remove(request,shop_id,info_id):
    shop=get_shop(request,shop_id)
    info = get_object_or_404(Info,shop=shop,id=info_id)
    info.delete()
    context = {'shop':shop}
    return redirect('infocards:info',shop_id)

templates/infocards/infocards.html
{% extends 'shops/layout.html' %}
{% block scripts %}
{% endblock %}
{% block content%}
<div>
    {% for category in shop.category_set.all %}
        <form action="{% url 'infocards:menu_remove' shop.id %}" method="post">
            {% csrf_token %}
            
            <div><h1>{{category}}</h1><button type="submit">삭제</button></div>
            {% comment %} type과 cat_id를 request.POST로 get해서 객체호출 {% endcomment %}
            <input type="text" name="type" value="category" style="display:none">
            <input type="text" name="cat_id" value="{{category.id}}" style="display:none">
        </form>
            
        <table style="margin:auto;">
            <th>메뉴이름</th>
            <th>메뉴설명</th>
            <th>가격</th>
            <th></th>
            <tbody>
                {% for menu in category.menu_set.all %}
                    <tr>
                        <td>{{menu}}</td>
                        <td>{{menu.content}}</td>
                        <td>{{menu.price}}원</td>
                        <td>
                            <form action="{% url 'infocards:menu_remove' shop.id %}" method="post">
                                {% csrf_token %}
                                    <button type="submit">삭제</button>
                                {% comment %} type과 cat_id를 request.POST로 get해서 객체호출 {% endcomment %}
                                <input type="text" name="type" value="menu" style="display:none">
                                <input type="text" name="men_id" value="{{menu.id}}" style="display:none">                            
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <form action="{% url 'infocards:infocard' shop.id %}" method="post">
            {% csrf_token %}
            <input type="text" name="type" value="menu" style="display:none">
            <input type="text" name="cat_id" value="{{category.id}}" style="display:none">
            <input type="text" name="name" placeholder='메뉴이름을 입력해주세요' value="{{men_form.name.value|default:''}}"><br>
            <input type="text" name="content" placeholder='메뉴설명을 입력해주세요' value="{{men_form.content.value|default:''}}"><br>
            <input type="number" name="price" placeholder='메뉴가격을 입력해주세요' value="{{men_form.price.value|default:''}}"><br>
            <button type="submit">확인</button>
        </form>
    {% endfor %}
    <form action="{% url 'infocards:infocard' shop.id %}" method="post">
        {% csrf_token %}
        <div>카테고리 입력란</div>
        <input type="text" name="type" value="category" style="display:none">
        <input type="text" name="name" placeholder='카테고리이름을 입력해주세요' value="{{cat_form.name.value|default:''}}"><br>
        <button type="submit">확인</button>
    </form>
</div>
{% endblock %}
{% block _scripts %}
{% endblock %}

templates/infocards/setinfo.html
{% extends 'shops/layout.html' %}
{% load bootstrap3 %}
{% block scripts %}
{% endblock %}
{% block content%}
    {% if shop.info_set.all %}
        {% for info in shop.info_set.all %}
        <div>
        {% if info.image %}
        <img style = "margin:auto;width:100px;height:100px; "src="{{info.image.url}}" alt="">
        {% endif %}
        {{info.content|linebreaks}}
        </div>
        <a href="{% url 'infocards:info_remove' shop.id info.id %}">삭제</a>
        <form action="{% url 'infocards:info_edit' shop.id info.id %}" method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}         
            <input type="submit" value="수정"/>
        </form>
        {% endfor %}
    {% else %}    
    <form action="{% url 'infocards:info' shop.id %}" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}         
        <input type="submit" value="확인"/>
    </form>
    {% endif %}
{% endblock %}
{% block _scripts %}
{% endblock %}