infocards/urls.py
from django.urls import path, re_path
from . import views
from . import models
app_name = 'infocards'

urlpatterns = [
    path('<int:shop_id>/settings/infocards',views.infocard,name="infocard"),
    path('<int:shop_id>/settings/menu/remove',views.menu_remove,name="menu_remove"),
    path('<int:shop_id>/settings/info',views.info,name="info"),    
    path('<int:shop_id>/settings/info_edit/<int:info_id>',views.info_edit,name="info_edit"),
    path('<int:shop_id>/settings/info_remove/<int:info_id>',views.info_remove,name="info_remove"),
]

shops/urls.py
from django.urls import path, re_path
from . import views
app_name = 'shops'

urlpatterns = [
    path('register/', views.shop_register, name = "register"),
    path('<int:shop_id>/',views.shop_admin_view,name="admin"),
    path('<int:shop_id>/settings/',views.shop_settings,name="settings"),
    path('<int:shop_id>/status/',views.set_shop_status,name="status"),
    
    
    path('<int:shop_id>/settings/location',views.shop_settings_location,name="location"),
    
    path('<int:shop_id>/remove/',views.shop_remove,name="shop_remove"),    
    path('render_list/',views.get_waiting_list,name='get_waiting_list'),
    path('remove',views.remove_waiting,name='remove'),
    path('call',views.call_waiting,name='call'),
    path('enter',views.enter_waiting,name='enter'),
    path('get_shops/',views.get_shops,name='get_shops'),
    path('get_address/',views.get_address,name='get_address'),
    path('get_biznum/',views.get_biznum,name='get_biznum'),
    path('filtered_shop',views.filter_shop,name='filter'),
    
    
    path('test',views.test,name='test'),
]

waitinghow/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from shops import views as shop_views
from clients import views as clients_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shops/', include('shops.urls')),
    path('waitings/', include('waitings.urls')),
    path('clients/', include('clients.urls')),
    path('infocards/', include('infocards.urls')),
    path('',clients_views.search_shops,name='search_main'),
    path('user_info',clients_views.search_shops,name='user_info'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/models.py
from django.db import models
from accounts.models import User
# Create your models here.

class Shop(models.Model):
    master = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('매장이름',max_length=100)
    bizNum=models.CharField('사업자등록번호',max_length=20,blank=True,null=True)
    zipNo = models.CharField('우편번호',max_length=10)
    address = models.CharField('매장위치',max_length=200)
    detailAddress = models.CharField('상세주소',max_length=200)
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    lat = models.CharField('위도',max_length=30)
    lng = models.CharField('경도',max_length=30)
    active = models.BooleanField(default=False)
    
    @classmethod
    def is_bizNum(cls,bizNum):
        try:
            shop = Shop.objects.get(bizNum=bizNum)
            return True
        except:
            return False
        
    def is_active(self):
        return self.active

    def __str__(self):
        return f"{self.name}"

shops/views.py
from django.contrib import messages
from django.http.request import HttpRequest
from django.http.response import JsonResponse
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.core.paginator import Paginator
from django.db.models import Q
from .functions import *
from waitings.models import *
from .models import *
from .form import *
from infocards.forms import *

@multiargs
def shop_register(request,*args,**kwargs):
    if request.method == 'POST':
        form = ShopRegisterForm(request.POST)  
        if form.is_valid():
            shop = form.save(commit=False)
            shop.master = request.user
            shop.save()
            Waiting.make_default(shop)
            context = {'method':'get'}
            return redirect('accounts:user_info')
    else:
        form = ShopRegisterForm()
    context = {'form':form}
    return render(request,'shops/register.html',context)

@multiargs
@owner_required
def shop_settings(request,*args,**kwargs):
    shop_id = kwargs['shop_id']
    shop=get_shop(request,shop_id)
    context={'shop':shop}
    return render(request,'shops/settings.html',context)

@owner_required
def shop_settings_location(request,shop_id):
    shop=get_shop(request,shop_id)
    if request.method == "POST":
        form = ShopRegisterForm(request.POST,instance=shop)
        name = request.POST.get('name')
        address = request.POST.get('address')
        if form.is_valid():
            if (name != '') and (address != ''):
                _shop = form.save(commit=False)
                _shop.save()
                messages.success(request,"수정되었습니다.")
                redirect('shops:location',shop_id)
    else:
        form = ShopRegisterForm(instance=shop)
    context={'shop':shop}
    return render(request,'shops/settings_location.html',context)

@owner_required
def shop_remove(request,shop_id):
    shops = Shop.objects.filter(master=request.user)
    context={'shops':shops}
    if request.method == "POST" and shop_id != 0:
        try:
            shop = get_object_or_404(Shop,master=request.user,id=shop_id)
            shop.delete()
            messages.warning(request,"삭제됨.")
            shops = Shop.objects.all()
            context={'shops':shops}
            return render(request,'shops:shop_delete',context)
        except:
            return redirect('search_main')
    return render(request,'shops/shop_delete.html',context)

@owner_required
def shop_admin_view(request,shop_id):
    shop=get_shop(request,shop_id)
    waitings_list = shop.waiting_set.all()
    context={'waitings_list':waitings_list,'shop':shop}
    return render(request,'shops/admin.html',context)

def get_waiting_list(request: HttpRequest):
    id = request.GET.get('from_id')
    shop_id = request.GET.get('shop_id')
    shop =get_shop(request,shop_id)
    _waiting_list = Waiting.objects.all().filter(id__gt=id,is_disposed=False,shop_name=shop).order_by('id')
    if _waiting_list.exists():
        waiting_list = list(_waiting_list.values())
    else:
        waiting_list = []
    return JsonResponse({
        'resultCode': "S-1",
        'waitings': waiting_list,
    })
    
@owner_required
def set_shop_status(request,shop_id):
    shop=get_shop(request,shop_id)
    shop.active = not shop.active
    shop.save()
    return redirect('accounts:user_info')
    
    
@owner_required
def remove_waiting(request):
    shop_id = request.GET.get('shop_id')
    message_id = request.GET.get('message_id')
    waiting = get_object_or_404(Waiting,id=message_id)
    waiting.delete_waiting()
    #카카오알림API로 취소 메세지 전송 구현해야함.
    #Waiting모델 메소드로 구현예정
    return redirect('shops:admin',shop_id=shop_id)

@owner_required
def call_waiting(request):
    shop_id = request.GET.get('shop_id')
    message_id = request.GET.get('message_id')
    whereami = len(Waiting.objects.filter(shop_name=shop_id,id__lt=message_id,is_entered=False,is_disposed=False))
    waiting = Waiting.objects.get(id=message_id)
    waiting.call_waiting(whereami)
    # Waiting모델의 메소드로 api콜 구현 예정
    # #카카오알림API로 취소 메세지 전송 구현해야함.
    # messages.success(request,f"{shop_id} : {message_id}")
    return redirect('shops:admin',shop_id=shop_id)

@owner_required
def enter_waiting(request):
    shop_id = request.GET.get('shop_id')
    message_id = request.GET.get('message_id')
    waiting = get_object_or_404(Waiting,id=message_id)
    waiting.enter_waiting()
    # waiting = Waiting.objects.get(id=message_id)
    # Waiting모델의 메소드로 api콜 구현 예정
    # #카카오알림API로 취소 메세지 전송 구현해야함.
    # messages.success(request,f"{shop_id} : {message_id}")
    return redirect('shops:admin',shop_id=shop_id)

def get_address(request):
    """
    도로명주소 검색 API서비스를 위한 함수입니다.
    """
    keyword = request.GET.get('keyword')
    page = request.GET.get('page')
    perPage = request.GET.get('perPage')
    locations = get_location(keyword,page,perPage)
    total_count = locations[-1]
    return JsonResponse({
        'resultCode': "S-1",
        'locations': locations[0],
        'total_count':total_count,
    })

def get_biznum(request):
    keyword = request.GET.get('keyword')
    biz_num,status = get_business_number(keyword)
    return JsonResponse({
        'resultCode': "S-1",
        'biz_num': biz_num,
        'status': status,
    })
    
def get_shops(request):
    """
    메인화면의 검색기능을 위한 함수입니다.
    """
    try:
        shop_name = request.GET.get('shop_name')
        page = int(request.GET.get('page'))
        perPage = int(request.GET.get('perPage'))
        shop_list=Shop.objects.filter(Q(name__icontains=shop_name)|Q(address__icontains=shop_name)).values()
        paginator = Paginator(shop_list,perPage)
        paged_shop_list = paginator.page(page)
        _shop = list(paged_shop_list)
        total_count = len(shop_list)
    except:
        return JsonResponse({
                'resultCode':"F-1",
                'shop':'',
                'shop_name':shop_name,
                'page':page,
                'perPage':perPage,
                'total_count':'0',
            })
    else:
        return JsonResponse({
            'resultCode':"S-1",
            'shop':_shop,
            'total_count':total_count,
        })
        
def filter_shop(request):
    """
    카카오맵에서 메인마커 주변에 위치한 매장의 정보를 받아오기 위한 함수입니다.
    """
    lat = float(request.GET.get('lat'))
    lng = float(request.GET.get('lng'))
    _range = float(request.GET.get('range'))
    range = _range**2*_range/800
    infos = []
    _shop = Shop.objects.filter(lat__gt=lat-range,lat__lt=lat+range,lng__gt=lng-range,lng__lt=lng+range)
    shop = list(_shop.values())
    for i in _shop:
        tmp = list(i.info_set.all().values())
        infos.append(tmp)
    
    return JsonResponse({
        'resultCode':"S-1",
        'shop':shop,
        'infos':infos,
        'range':range,
        'empty':'empty'
    })

templates/shops/addr_finder.html
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=2a4ee9232f3e8338415d61da0903a7c9&libraries=services"></script>
<script type="text/javascript">
    let page = 1;
    let perPage = 5;
    let total_count = 0;
    function get_bizNum(){
        $.get(
            '{% url "shops:get_biznum" %}',
            {  
                'keyword':$('#biz_num').val(),
            },
            function(data){
                //console.log(data['status'])
                if (data['status']==true){
                    $('#fixed_bizNum').val(data['biz_num']);
                    $('#fixed_bizNum').next().val(data['biz_num']);
                }else{
                    alert("검색 결과가 없습니다.")
                }
            },
            'json'
        )
    }
    function get_address(){
        $.get(
            '{% url "shops:get_address" %}',
            {  
                'keyword':$('#location').val(),
                'page':page,
                'perPage':perPage,
            },
            function(data){
                //console.log(data)
                $('#render_location').html('');
                total_count = data.total_count;//마지막 페이지를 찾기 위함.
                render_location(data);
            },
            'json'
        )
    }
    function render_location(data){
        html = '';
        idx = 1;
        if (data.total_count!='0'){
            for (let locationKey in data.locations){
                let location = data.locations[locationKey]['roadAddr'];
                html += (`
                    <li id ='location${idx}' data-location="${location}"
                    data-zipNo="${data.locations[locationKey]['zipNo']}">
                        <span>도로명</span><span> : ${location}</span><br>
                        <span>지번</span><span>  :${data.locations[locationKey]['jibunAddr']}</span><br>
                        <button onclick=fixing_location(${idx})>선택</button>
                    </li>
                `);
                idx++;
            }
            // 이전 - 다음페이지 구현
            if (page >1){
                html +=(`<button onclick=page_set(-1)>이전페이지</button>`);
            }else{
                html +=(`<button disabled>이전페이지</button>`);
            }
            html +=(`<span>[${page}]</span>`)
            if((total_count - page*perPage)>=0){
                html +=(`<button onclick=page_set(1)>다음페이지</button>`);
            }else{
                html +=(`<button disabled>다음페이지</button>`);
            }
            $('#render_location_here').html(html);
        }else{
            $('#render_location_here').html('<div>정보가 없습니다</div>');
        }
    }
    function page_set(page_val){
        //페이지 전역변수를 통해 페이지제어
        page = page + page_val;
        get_address();
    }
    function fixing_location(idx){
        _zipNo=$('#location'+idx).attr("data-zipNo");
        _addr = $('#location'+idx).attr("data-location");
        $('#fixed_zipNo').val(_zipNo);
        $('#fixed_address').val(_addr);
        $('#fixed_zipNo').next().val(_zipNo);
        $('#fixed_address').next().val(_addr);
        $('#render_location_here').html('');
        show_cur_location(_addr)
        
    }
    var container = document.getElementById('map');
    var options = {
        center: new kakao.maps.LatLng(33.450701, 126.570667),
        level: 3,
        mapTypeId : kakao.maps.MapTypeId.ROADMAP
    };

    var map = new kakao.maps.Map(container, options);    
    var markers = [];
    var infoWindows = [];

    //kakao api
    function locationLoadSuccess(pos){
        // 현재 위치 받아오기
        var currentPos = new kakao.maps.LatLng(pos.coords.latitude,pos.coords.longitude);

        // 지도 이동(기존 위치와 가깝다면 부드럽게 이동)
        map.panTo(currentPos);

        // 결과값으로 받은 위치를 마커와 인포 윈도우로 표시합니다
        make_marker(currentPos,"현재위치");

    };

    function locationLoadError(pos){
        alert('위치 정보를 가져오는데 실패했습니다.');
    };

    // 위치 가져오기 버튼 클릭시
    function getCurrentPosBtn(){
        navigator.geolocation.getCurrentPosition(locationLoadSuccess,locationLoadError);//위치정보 가져오는 함수.
    };

    //입력된 주소를 kakao 맵에 표시합니다.
    function show_cur_location(_addr){
    // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();

        // 주소로 좌표를 검색합니다 ajax를 사용함으로 비동기콜백을이용함
        geocoder.addressSearch(_addr, function(result, status) {

            // 정상적으로 검색이 완료됐으면 
            if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);  

                // 결과값으로 받은 위치를 마커와 인포 윈도우로 표시합니다
                make_marker(coords,"현재위치");

            }else{
                getCurrentPosBtn();
            }
        });
    }
    function make_marker(xz,praise){
        var marker = new kakao.maps.Marker({
            map: map,
            draggable:true,
            position: xz
        });
        infowindow = new kakao.maps.InfoWindow({
            content: `<div style="width:150px;text-align:center;padding:6px 0;">${praise}</div>`
        });      
        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다 
        map.panTo(xz);  
        // 기존의 마커와 인포창들을 닫습니다.
        closeMarkers();
        closeInfowindows();
        kakao.maps.event.addListener(marker, 'dragend', function() {
            // 출발 마커의 드래그가 종료될 때 마커 이미지를 원래 이미지로 변경합니다
            _cur_loc = marker.getPosition();
            make_marker(_cur_loc,"현재위치")
        });
        // 마커와 인포창 배열에 마커와 인포창을 추가합니다.
        infoWindows.push(infowindow)    
        markers.push(marker)
        // 마커와 인포창을 맵에 표시합니다.
        infowindow.open(map, marker);   
        marker.setMap(map); 
        $('#lat').val(xz['Ma']);
        $('#lng').val(xz['La']);
    }
    function closeMarkers() {
        for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
        }            
    }
    function closeInfowindows() {
        for (var i = 0; i < infoWindows.length; i++) {
            infoWindows[i].close()
        }            
    }
    show_cur_location($('#fixed_address').val());
</script>

templates/shops/admin.html
{% extends 'shops/layout.html' %}
{%load tags %}
{% block scripts %}
{% endblock %}
{% block content %}
<div class = "waiting-table">
    <div id = "dataset" data-value = "{{shop.id}}" style="display:none"></div>
    {% if waitings_list %}
    <div class="waiting-admin  mx-wr">
    </div>
    {%else%}
    <div>대기중인 손님이 없어요</div>
    {%endif%}
</div>
{% endblock %}
{% block _scripts %}
{% include 'shops/admin_logic.html' %}
{% endblock %}

templates/shops/admin_logic.html
d<script type="text/javascript">
    let WaitingList__lastWaitingId = 0;
    let shop_id = $('#dataset').attr('data-value');
    function WaitingList__loadMore() {
        $.get(
            '{% url "shops:get_waiting_list" %}', 
            {
                from_id: WaitingList__lastWaitingId,
                shop_id,
            },
            function(data) {
                console.log(data)
                for ( let waitingKey in data.waitings ) {
                    const waiting = data.waitings[waitingKey];
                    WaitingList__lastWaitingId = waiting.id;
                    console.log(WaitingList__lastWaitingId);
                    WaitingList__renderMessage(waiting,waitingKey);
                }    
                setTimeout(WaitingList__loadMore, 1000);
            },
            'json'
        );
    }
    function WaitingList__renderMessage(message,waitingKey) {
        console.log("호출여부",message['is_called']);
        $('.waiting-admin').append(`
        <div class="flex waiting-row gotgam">
            <div class="waiting-td m-auto">
                <div>
                ${parseInt(waitingKey)+1}.
                <span class="mx-1000-word">번</span>
                </div>
            </div>
            <div class="waiting-td m-auto">
                ${message.how_many}
                <span class="mx-1000-word">명</span>
            </div>
            <div class="waiting-td">`
                +WaitingList__ActionForm(message,"{% url 'shops:enter' %}","입장","fas fa-sign-in-alt")+
            `</div>
            <div class="waiting-td">`
                +WaitingList__ActionForm(message,"{% url 'shops:remove' %}","제거","fas fa-trash")+
            `</div>
            <div class="waiting-td">`
                +WaitingList__ActionForm(message,"{% url 'shops:call' %}","호출","fas fa-envelope")+
            `</div>
            <div class="waiting-td">`
                +is_called(message)+
            `</div>
        </div>`);
    }
    function WaitingList__ActionForm(message,url,syntax,fontawesome){
        
        context = `            
            <form action=${url} onsubmit="WaitingList_Action(this); return false;">
                <input type="text" style="display:none" style=""name="message_id" value='${message.id}'>
                <input type="text" style="display:none" style=""name="shop_id" value={{shop.id}}>
                <button type="submit" class = "searchButton">
                    <span class="mx-waiting-words gotgam">${syntax}</span>
                    <i class="${fontawesome} mx-waiting-icons"></i>
                </button>
            </form>  
        `
        return context;
    }
    function is_called(message){
        if(message['is_called']){
           context =  `<div class="searchButton"><i class="safe fas fa-bell"></i>
           </div>`
        }else{
            context =  `<div class="searchButton ">
                <i class="warn far fa-bell"></i>
            </div>`
        }
        return context
    }
    WaitingList__loadMore();
</script>

templates/shops/layout.html
{% extends 'layout.html' %}
{% block head_scripts %}
{% block scripts %}
{% endblock %}
{% endblock %}
{% block head_styles %}
{% block styles %}
{% endblock %}
{% endblock %}
{% block app %}
    {% if shop %}
        <div style="text-align:center;">
            {% comment %} 매장이름 크게 박아줄수있어요? {% endcomment %}
            <h1 style="margin:auto;">{{shop.name}}</h1>
        </div>
    {% endif %}
{% block content %}
{% endblock %}
{% endblock %}
{% block foot_scripts %}
{% block _scripts %}
{% endblock  %}
{% endblock %}

templates/shops/register.html
{% extends 'shops/layout.html' %}
{% block scripts %}
{% endblock %}
{% block content%}
<style>
    input[type="text"]{
        padding: 5px 10px;
        margin-bottom: 15px;
    }
</style>
<div>
    <div>
        <form action="{% url 'shops:register' %}" method="post">
            {% csrf_token %}
            <div>가게이름</div>
            <input type="text" name = "name" value="{{ form.name.value|default:''}}" autocomplete="off"/>
            <div>사업자번호</div>
            <input type="text" name = "bizNum" id = "fixed_bizNum" value="{{ form.bizNum.value|default:''}}" autocomplete="off" disabled/>
            <input type="text" name = "bizNum" id = "fixed_bizNum"value="{{ form.bizNum.value|default:''}}" autocomplete="off" style="display:none"/>
            <div>우편번호</div>
            <input type="text" name = "zipNo1" id = "fixed_zipNo" value="{{ form.zipNo.value|default:''}}" disabled >
            <input type="text" name = "zipNo" id = "fixed_zipNo" value="{{ form.zipNo.value|default:''}}" style="display:none">
            <div>도로명주소</div>
            <input type="text" name = "address1" id = "fixed_address" value="{{ form.address.value|default:''}}" disabled>
            <input type="text" name = "address" id = "fixed_address" value="{{ form.address.value|default:''}}" style="display:none">
            <div>상세주소</div>
            <input type="text" name = "detailAddress" id = "detailAddress" value="{{ form.detailAddress.value|default:''}}" placeholder="ex)매화빌딩 103호">
            <input type="text" name = "lat" id = "lat" value="{{ form.lat.value|default:''}}" style="display:none"/>
            <input type="text" name = "lng" id = "lng" value="{{ form.lng.value|default:''}}" style="display:none"/>
            <br>
            <button type="submit">확인</button>
        </form>
        <form method="get"onsubmit= "get_bizNum();return false">
            <div>사업자번호 검색</div>
            <input type="number" id = "biz_num" name = "biz_num"
            value="{{ form.biz_num.value|default_if_none:''}}" autocomplete="off"
            placeholder="ex)123-456-7890"/>
            <button>사업자번호확인</button>
        </form>
        <form method="get"onsubmit= "page = 1;get_address();return false">
            <div>주소 검색</div>
            <input type="text" id = "location" name = "location"
            value="{{ form.location.value|default_if_none:''}}" autocomplete="off"
            placeholder="ex)대성동, 둔산동"/>
            <button>주소확인</button>
        </form>
        <div id='render_location_here'></div><input type='number' style='display:none'id='location_page' value=1>
        
        <div id="map" style="width:500px;height:400px;margin:auto;"></div>
        
    </div>
    //가게정보등록창//
</div>
{% endblock %}

{% block _scripts %}
{% include 'shops/addr_finder.html' %}
{% endblock %}

templates/shops/settings.html
{% extends 'shops/layout.html' %}
{% block scripts %}
{% endblock %}
{% block content%}
<div>
    가게 정보 수정 창이에요
    <form action="{% url 'shops:location' shop.id %}"method="get">
        <button type='submit' class="searchButton m-50">위치수정</button>
    </form>
    <form action="{% url 'infocards:infocard' shop.id %}"method="get">
        <button type='submit' class="searchButton m-50">메뉴수정</button>
    </form>
    <form action="{% url 'infocards:info' shop.id %}"method="get">
        <button type='submit' class="searchButton m-50">소개수정</button>
    </form>
</div>
{% endblock %}
{% block _scripts %}
{% endblock %}

templates/shops/settings_location.html
{% extends 'shops/layout.html' %}
{% block scripts %}
{% endblock %}
{% block content%}
<div>
    가게 정보 수정 창이에요
    <form action="{% url 'shops:location' shop.id %}"method="post">
        {% csrf_token %}
            <div>가게이름</div>
            <input type="text" name = "name" value="{{shop.name}}" autocomplete="off"/>
            <div>사업자번호</div>
            <input type="text" name = "bizNum" id = "fixed_bizNum" value="{{ shop.bizNum|default:''}}" autocomplete="off" disabled/>
            <input type="text" name = "bizNum" id = "fixed_bizNum"value="{{ shop.bizNum|default:''}}" autocomplete="off"style="display:none"/>
            <div>우편번호</div>
            <input type="text" name = "zipNo1" id = "fixed_zipNo" value="{{shop.zipNo}}" disabled>
            <input type="text" name = "zipNo" id = "fixed_zipNo" value="{{shop.zipNo}}" style="display:none">
            <div>도로명주소</div>
            <input type="text" name = "address1" id = "fixed_address" value="{{shop.address}}" disabled>
            <input type="text" name = "address" id = "fixed_address" value="{{shop.address}}" style="display:none">
            <div>상세주소</div>
            <input type="text" name = "detailAddress" id = "detailAddress" value="{{ shop.detailAddress|default:''}}" placeholder="ex)매화빌딩 103호"><br>
            <input type="text" name = "lat" id = "lat" value="{{ form.lat.value|default:''}}" style="display:none"/>
            <input type="text" name = "lng" id = "lng" value="{{ form.lng.value|default:''}}" style="display:none"/>
            <input type="submit" value="확인"/>
        </div> 
    </form>
    <form method="get"onsubmit= "get_bizNum();return false">
        <div>사업자번호 검색</div>
        <input type="number" id = "biz_num" name = "biz_num"
        value="{{ form.biz_num.value|default_if_none:''}}" autocomplete="off"
        placeholder="ex)123-456-7890"/>
        <button>사업자번호확인</button>
    </form>
    <form method="get"onsubmit= "page = 1;get_address();return false">
        <div>주소 검색</div>
        <input type="text" id = "location" name = "location"
        value="{{ form.location.value|default_if_none:''}}" autocomplete="off"
        placeholder="ex)대성동, 둔산동"/>
        <button>주소확인</button>
    </form>
    <div id='render_location_here'></div><input type='number' style='display:none'id='location_page' value=1>
        
    <div id="map" style="width:500px;height:400px;margin:auto;"></div>
        
</div>
{% endblock %}
{% block _scripts %}
{% include 'shops/addr_finder.html' %}
{% endblock %}

templates/shops/shop_delete.html
{% extends 'shops/layout.html' %}
{% block content%}
{% for shop in shops %}
<form action="{% url 'shops:shop_remove' shop.id  %}" method="post">
    {% csrf_token %}
    <div>{{shop.name}}</div>
    <button type='submit'>매장삭제</button>
</form>
{% endfor %}
{% endblock %}

templates/shops/test.html
{% load tags %}
<script type="text/javascript">
    function test(){
        console.log({{shop|obj}});
    }
    test()
</script>