shops/urls.py
from django.urls import path, re_path
from . import views
app_name = 'shops'

urlpatterns = [
    path('register/', views.shop_register, name = "register"),
    path('<int:shop_id>/',views.shop_admin_view,name="admin"),
    path('<int:shop_id>/settings/',views.shop_settings,name="settings"),
    path('<int:shop_id>/status/',views.set_shop_status,name="status"),
    
    
    path('<int:shop_id>/settings/location',views.shop_settings_location,name="location"),
    
    path('<int:shop_id>/remove/',views.shop_remove,name="shop_remove"),    
    path('render_list/',views.get_waiting_list,name='get_waiting_list'),
    path('remove',views.remove_waiting,name='remove'),
    path('call',views.call_waiting,name='call'),
    path('enter',views.enter_waiting,name='enter'),
    path('get_shops/',views.get_shops,name='get_shops'),
    path('get_address/',views.get_address,name='get_address'),
    path('get_biznum/',views.get_biznum,name='get_biznum'),
    path('filtered_shop',views.filter_shop,name='filter'),
    
    
    path('test',views.test,name='test'),
]

waitinghow/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views
from shops import views as shop_views
from clients import views as clients_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shops/', include('shops.urls')),
    path('waitings/', include('waitings.urls')),
    path('clients/', include('clients.urls')),
    path('infocards/', include('infocards.urls')),
    path('',clients_views.search_shops,name='search_main'),
    path('user_info',clients_views.search_shops,name='user_info'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waitings/urls.py
from django.urls import path, re_path
from . import views

app_name = 'waitings'
#
urlpatterns = [
    path('<int:shop_id>/views', views.customer_views, name = "views"),
    path('<int:shop_id>/add/waiting', views.add_waiting, name = "add_waiting"),
    path('<int:shop_id>/add/people', views.add_people, name = "add_people"),
    path('showteams/',views.show_teams,name="show_teams"),
    path('<int:shop_id>/add/remote',views.customer_views,name="remote")
]

waitings/models.py
from django.db import models
from django.shortcuts import render, get_object_or_404
from django.core.validators import MaxValueValidator
from django.contrib import messages
from shops.models import Shop
from solapi.send_sms import send_message
# Create your models here.


class Waiting(models.Model):
    phone_number = models.CharField('전화번호',max_length=12)
    how_many = models.PositiveIntegerField('예약인수',null=True)
    adults = models.PositiveIntegerField('성인',null=True)
    kids = models.PositiveIntegerField('유아',null=True)
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    is_entered = models.BooleanField('입장여부')
    is_disposed = models.BooleanField('처리여부')
    shop_name = models.ForeignKey(Shop,on_delete=models.CASCADE)
    client = models.ForeignKey('accounts.User',on_delete=models.CASCADE,null=True,blank=True,related_name="waitings_set")
    is_called = models.BooleanField('호출여부',default=False,null=True,blank=True)
    @classmethod
    def make_default(cls,shop):
        Waiting(phone_number=0,how_many=0,adults=0,kids=0,is_entered=False,shop_name=shop,is_disposed=True).save()
    @classmethod
    def is_waiting(cls,phone_number):
        try:
            waiting = Waiting.objects.get(phone_number=phone_number,is_disposed=False)
            return True
        except:
            return False
    @classmethod
    def show_phone_number(cls,phone_number):
        qoute = '-'
        if len(phone_number)==11:
            result = phone_number[0:3]+qoute+phone_number[3:7]+qoute+phone_number[7:11]
        if len(phone_number)==10:
            result = phone_number[0:3]+qoute+phone_number[3:6]+qoute+phone_number[6:10]
        return result
    def delete_waiting(self):
        '''
        phone_number에 적힌 번호를 기준으로 카카오톡 알림api호출
        '''
        self.is_entered = False
        self.is_disposed = True
        self.save()
    def enter_waiting(self):
        '''
        phone_number에 적힌 번호를 기준으로 카카오톡 알림api호출
        '''
        self.is_entered = True
        self.is_disposed = True
        self.save()
    def call_waiting(self,number):
        '''
        phone_number에 적힌 번호를 기준으로 카카오톡 알림api호출
        '''
        context = f"{self.shop_name}의 대기열이 {number}팀 남았습니다."
        if "000" not in self.phone_number:
            send_message(self.phone_number,context)
        self.is_called = True
        self.save()

waitings/forms.py
from django import forms
from .models import Waiting

class PeopleGetForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone_number'].required = True
        self.fields['adults'].required = True
        self.fields['kids'].required = True

    class Meta:
        model = Waiting
        fields = ['phone_number','adults', 'kids']

waitings/views.py
from django.forms import ValidationError
from django.shortcuts import get_object_or_404, render ,redirect
from django.contrib import messages
from django.http import HttpRequest,HttpResponse,JsonResponse
from shops.models import Shop
from waitings.models import Waiting
from .forms import *
from shops.functions import owner_required,active_required
from django.contrib.auth.decorators import login_required
# Create your views here.

@active_required
@login_required
def customer_views(request,shop_id):
    shop = Shop.objects.get(id=shop_id)
    context ={'shop':shop}
    return render(request,'waitings/views.html',context)

##매장 주인이 아닐시, 로그인 되어있으면 자동으로 자기 전화번호 입력.
@active_required
@login_required
def add_waiting(request,shop_id):        
    shop = Shop.objects.get(id=shop_id)
    phone_number = request.POST.get('phone_number')
    context= {'shop':shop,'phone_number':phone_number}
    # if not Shop.objects.filter(master=request.user,shop_id=shop_id):
    #     context += {'phone_number':request.user.phone_number}
    #     return render(request,'waitings/howmany.html',context)
    if request.method == 'POST':
        if Waiting.is_waiting(phone_number):
            messages.warning(request,f"이미 예약중입니다.")
            return render(request,'waitings/views.html',context)            
        if len(phone_number)<10:
            messages.warning(request,"전화번호가 너무 짧습니다.")
            return render(request,'waitings/views.html',context)            
        request.POST.adults = "0"
        request.POST.kids = "0"
        return render(request,'waitings/howmany.html',context)
    return render(request,'waitings/views.html',context)
@active_required
@login_required
def add_people(request,shop_id):    
    shop = Shop.objects.get(id=shop_id)
    _phone_number = request.POST.get('phone_number')
    adults = request.POST.get('adults')
    kids = request.POST.get('kids')
    if adults == "0" and kids == "0":
        context = {'phone_number':_phone_number,'shop':shop}
        return render(request,'waitings/howmany.html',context)
    how_many = int(adults)+int(kids)
    waiting = Waiting(phone_number=_phone_number,how_many=how_many,
            adults=adults,kids=kids,is_entered=False,
            shop_name=shop,is_disposed=False)
    #shop_id와 request.user가 일치하지 않으면 waiting.client=request.user
    if shop.master != request.user:
        waiting.client = request.user
    waiting.save()
    context = {'shop':shop}
    messages.success(request,"예약되었습니다.")
    return redirect('waitings:views',shop_id=shop.id)
    

def show_teams(request):
    shop_id = request.GET.get('shop_id')
    shop = Shop.objects.get(id=shop_id)
    waiting_list = Waiting.objects.filter(is_disposed=False,shop_name=shop)
    peoples = 0
    for i in waiting_list:
        peoples += i.how_many
    return JsonResponse({
        'resultCode': "S-1",
        'peoples' : str(peoples),
        'teams' : str(len(waiting_list)),
    })
    
@active_required
@login_required
def remote_waiting(request,shop_id):
    shop = get_object_or_404(Shop,id=shop_id)
    context={'shop':shop}
    return render(request,'waitings/remote.html',context)

templates/waitings/howmany.html
{% extends 'waitings/layout.html' %}
{% block scripts %}
{% include 'waitings/howmany_logic.html' %}
{% endblock %}
{% block content%}

<div>
    <div id = "dataset" data-value = "{{shop.id}}" style="display:none"></div>
    <div>
        <form class="iamform"action="{% url 'waitings:add_people' shop.id %}" method="post">
            {% csrf_token %}
            <div>
                <div>성인</div>
                <input type="text" name = "phone_number" value="{{request.POST.phone_number}}" style = "display:none">

                <button class="adults_minus searchButton">
                    <i class="fas fa-minus"></i>
                </button>
                <input type="number" autocomplete='off' class = "adults searchBox w-500" name = "adults" value=0 min="0">
                <button class="adults_plus searchButton">
                    <i class="fas fa-plus"></i>
                </button>      
            </div>
            <div>
                <div>유아</div>
                <button class="kids_minus searchButton">
                    <i class="fas fa-minus"></i>
                </button>
                <input type="number" autocomplete='off' class = "kids searchBox w-500" name = "kids" value=0>
                <button class="kids_plus searchButton">
                    <i class="fas fa-plus"></i>
                </button>
            </div>
            <div class="flex flex-ai-c flex-jc-c">
                <a class="searchButton m-50" href="{% url 'waitings:views' shop.id %}">
                    <i class="fas fa-backspace"></i>
                </a>
                <button type="submit" class="searchButton m-50" value = "작성">
                    <i class="fas fa-check-circle"></i>
                </button>
            </div>
        </form>
    </div>
    <div>
    </div>
</div>
{% endblock %}
{% block _scripts %}
{% include 'waitings/inspector_scripts.html' %}
{% endblock %}

templates/waitings/howmany_logic.html
<script type="text/javascript">
$(function(){
    $('.adults_plus').click(function(evt) {
        $('.adults').each(function(idx, ele) {
            $(ele).val(parseInt($(ele).val())+1);
        });
        evt.preventDefault();
    });
    $('.adults_minus').click(function(evt) {
        if($('.adults').val()>0){
            $('.adults').each(function(idx, ele) {
                $(ele).val(parseInt($(ele).val())-1);
            });
            evt.preventDefault();
        }
        return false;
    });
    $('.kids_plus').click(function(evt) {
        $('.kids').each(function(idx, ele) {
            $(ele).val(parseInt($(ele).val())+1);
        });
        evt.preventDefault();
    });
    $('.kids_minus').click(function(evt) {
        if($('.kids').val()>0){
            $('.kids').each(function(idx, ele) {
                $(ele).val(parseInt($(ele).val())-1);
            });
            evt.preventDefault();
        }
        return false;
    });
});
</script>

templates/waitings/inspector.html
{% load sum %}
<div class='how-many-teams'>
    {% comment %}
    inspector_scripts에 본문이있어요
    {% endcomment %}
</div>

templates/waitings/inspector_scripts.html
{% load sum %}
<script type='text/javascript'>
    shop_id = $('#dataset').attr('data-value');
    function HowManyTeams__loadMore() {
        $.get(
            "{% url 'waitings:show_teams' %}", 
            {shop_id},
            function(data){
                render(data);
                setTimeout(HowManyTeams__loadMore, 1000);
            }
            ,
            'json'
        );
    }
    function render(data) {
        $('.how-many-teams').html(`
        <div>
            <div>
                대기팀 : 
                ${data.teams}팀
            </div>
            <div>
                대기인 :
                ${data.peoples}명
            </div>
        </div> 
        `);
    }
    HowManyTeams__loadMore();
    $(document).ready(function() {
        $(document).click(function(e){
            $('.dd').focus();
            console.log('test')
        });
    });

</script>

templates/waitings/layout.html
{% extends 'layout.html' %}
{% block head_scripts %}
{% block scripts %}
{% endblock %}
{% endblock %}
{% block head_styles %}
{% block styles %}
{% endblock %}
{% endblock %}
{% block app %}
    {% if shop %}
    {% comment %}
    매장에 관한 링크에 들어갔을때
    최상단에 뜨는 구역이에요    
    {% endcomment %}
        <div style="text-align:center;">
            {% comment %}
            매장이름 크게 박아줄수있어요?
            {% endcomment %}
            <h1 style="margin:auto;">{{shop.name}}</h1>
        </div>
    {% endif %}
    {% include 'waitings/inspector.html' %}
{% block content %}
{% endblock %}
{% endblock %}
{% block foot_scripts %}
{% block _scripts %}
{% endblock  %}
{% endblock %}

templates/waitings/views.html
{% extends 'waitings/layout.html' %}
{% block content %}
<div>
    <div id = "dataset" data-value = "{{shop.id}}" style="display:none"></div>
    <div>
        <form id = "form" action="{% url 'waitings:add_waiting' shop.id %}" method="post">
            {% csrf_token %}
            
            <input type="number" class='dd searchBox w-500' autocomplete='off' name = "phone_number" placeholder="전화번호 입력"value ="{{ request.POST.phone_number|default_if_none:'' }}" >
            <button type="submit" class = "searchButton">
                <i class="fas fa-arrow-right"></i>
            </button>
        </form>
    </div>
</div>
{% endblock %}
{% block _scripts %}
{% include 'waitings/inspector_scripts.html' %}
{% endblock %}